# Generated by Django 5.0.2 on 2025-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chat_id', models.CharField(max_length=70, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Ник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
