# Generated by Django 5.0.2 on 2025-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusermodel',
            name='chat_id',
            field=models.CharField(max_length=70, unique=True, verbose_name='ID'),
        ),
    ]
