# Generated by Django 5.0.2 on 2025-06-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_telegramusermodel_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramusermodel',
            options={'verbose_name': 'Телеграм', 'verbose_name_plural': 'Телеграм'},
        ),
        migrations.AlterField(
            model_name='telegramusermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ник'),
        ),
    ]
