# Generated by Django 5.0.2 on 2025-06-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramusermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusermodel',
            name='balance',
            field=models.PositiveIntegerField(default=2, verbose_name='Баланс запросов'),
        ),
    ]
