# Generated by Django 5.0.2 on 2025-06-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramusermodel_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramusermodel',
            old_name='nickname',
            new_name='username',
        ),
    ]
