# Generated by Django 5.0.2 on 2025-08-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_nickname_telegramusermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusermodel',
            name='is_trader',
            field=models.BooleanField(default=False, help_text='Имеет доступ к трейд-разделу', verbose_name='Статус трейдера'),
        ),
    ]
