# Generated by Django 5.0.2 on 2025-08-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_telegramusermodel_is_trader'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('main_menu', models.BooleanField(default=False, verbose_name='Главное меню')),
                ('glaz_menu', models.BooleanField(default=False, verbose_name='Глаз бога')),
                ('receipt_menu', models.BooleanField(default=False, verbose_name='Чеки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.telegramusermodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступы к боту',
                'verbose_name_plural': 'Доступы к боту',
            },
        ),
    ]
