# Generated by Django 5.0.2 on 2025-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_botpermissionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusermodel',
            name='is_trader',
            field=models.BooleanField(default=False, help_text='Имеет полный доступ к боту', verbose_name='Статус трейдера'),
        ),
    ]
