# Generated by Django 5.2.7 on 2025-10-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_telegramusermodel_is_trader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botpermissionmodel',
            old_name='create_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='botpermissionmodel',
            old_name='update_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='telegramusermodel',
            old_name='create_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='telegramusermodel',
            old_name='update_on',
            new_name='updated_at',
        ),
    ]
