# Generated by Django 5.2.7 on 2025-10-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Пример: BTCUSDT', max_length=40, verbose_name='Название')),
                ('is_active', models.BooleanField(help_text='Разрешено открытие новых позиций', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Символ',
                'verbose_name_plural': 'Символы',
            },
        ),
        migrations.CreateModel(
            name='BanSymbolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('key', models.CharField(max_length=40, verbose_name='Блокировка')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='setting.symbolmodel', verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Блокировка символа',
                'verbose_name_plural': 'Блокировки символа',
            },
        ),
    ]
