# Generated by Django 5.2.7 on 2025-10-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bansymbolmodel',
            old_name='create_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bansymbolmodel',
            old_name='update_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='symbolmodel',
            old_name='create_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='symbolmodel',
            old_name='update_on',
            new_name='updated_at',
        ),
    ]
