# Generated by Django 5.2.7 on 2025-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_rename_create_on_bansymbolmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolmodel',
            name='qty',
            field=models.IntegerField(default=130, verbose_name='Сумма USDT для позиции'),
            preserve_default=False,
        ),
    ]
