# Generated by Django 5.2.7 on 2025-10-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_symbolmodel_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbolmodel',
            old_name='qty',
            new_name='qty_USDT_for_order',
        ),
    ]
