# Generated by Django 5.2.7 on 2025-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_rename_qty_symbolmodel_qty_usdt_for_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=40, verbose_name='Биржа')),
                ('base_url', models.URLField(verbose_name='Базовый URL')),
                ('maker_fee', models.FloatField(verbose_name='Комиссия мейкера')),
                ('taker_fee', models.FloatField(verbose_name='Комиссия тейкера')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
    ]
