# Generated by Django 5.2.7 on 2025-10-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_exchangemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemodel',
            name='target_percent',
            field=models.FloatField(default=0.5, verbose_name='Целевой процент'),
            preserve_default=False,
        ),
    ]
