# Generated by Django 5.2.7 on 2025-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_exchangemodel_target_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=40, verbose_name='Код')),
                ('prompt', models.TextField(verbose_name='Текст промпта')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
            },
        ),
    ]
