# Generated by Django 5.2.7 on 2025-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_promptmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=40, verbose_name='Индикатор')),
                ('json', models.JSONField(verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'Индикаторы',
                'verbose_name_plural': 'Индикаторы',
            },
        ),
    ]
