# Generated by Django 5.2.7 on 2025-11-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_settingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='value',
            field=models.IntegerField(default=1, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
