# Generated by Django 5.2.7 on 2025-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_settingsmodel_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'GPT',
                'verbose_name_plural': 'GPT',
            },
        ),
    ]
