# Generated by Django 5.2.7 on 2025-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_gptmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='context',
            field=models.BigIntegerField(default=1, verbose_name='Контекст'),
            preserve_default=False,
        ),
    ]
