# Generated by Django 5.0.2 on 2025-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
