# Generated by Django 5.2.7 on 2025-10-22 15:58

import django.db.models.deletion
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0006_alter_positionmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('category', models.CharField(max_length=20, verbose_name='Рынок')),
                ('side', models.CharField(max_length=6, verbose_name='Сторона')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('qty_tokens', models.CharField(max_length=255, verbose_name='Кол-во токенов')),
                ('status', django_fsm.FSMField(choices=[('created', 'Ожидание подтверждения'), ('monitoring', 'Мониторинг'), ('completed', 'Исполнено'), ('cancel', 'Отменено')], default='created', max_length=50, verbose_name='Статус')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='position.positionmodel', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
            },
        ),
    ]
