# Generated by Django 5.2.7 on 2025-10-27 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('action_name', models.CharField(max_length=255, verbose_name='Действие')),
                ('update_data', models.JSONField(verbose_name='Данные обновления')),
                ('comment', models.TextField(verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order.ordermodel', verbose_name='Ордер')),
            ],
            options={
                'verbose_name': 'История ордера',
                'verbose_name_plural': 'История ордера',
            },
        ),
    ]
