# Generated by Django 5.2.7 on 2025-10-27 01:30

import app.order.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_accumulated_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreditingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.CharField(choices=[('fee', 'Комиссия'), ('funding', 'Фандинг')], max_length=20, validators=[app.order.models.validate_type], verbose_name='Тип')),
                ('count', models.DecimalField(decimal_places=18, max_digits=40, verbose_name='Кол-во')),
                ('comment', models.TextField(verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crediting', to='order.ordermodel', verbose_name='Ордер')),
            ],
            options={
                'verbose_name': 'Зачисления',
                'verbose_name_plural': 'Зачисления',
            },
        ),
    ]
