# Generated by Django 5.2.7 on 2025-10-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordercreditingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='uuid',
            field=models.CharField(max_length=255, unique=True, verbose_name='UUID'),
        ),
    ]
