# Generated by Django 5.2.7 on 2025-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='accumulated_funding',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=40, verbose_name='Накопленный фандинг'),
        ),
    ]
