# Generated by Django 5.2.7 on 2025-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordermodel_accumulated_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='target_rate',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True, verbose_name='Цель для профита'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='category',
            field=models.CharField(default='option', max_length=20, verbose_name='Рынок'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.CharField(default='100000', max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='qty_tokens',
            field=models.CharField(default='0.00123', max_length=255, verbose_name='Кол-во токенов'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='side',
            field=models.CharField(default='sell', max_length=6, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='uuid',
            field=models.CharField(default='string', max_length=255, unique=True, verbose_name='UUID'),
        ),
    ]
