# Generated by Django 5.2.7 on 2025-10-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermodel_target_rate_alter_ordermodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='close_rate',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True, verbose_name='Курс закрытия'),
        ),
    ]
