# Generated by Django 5.2.7 on 2025-10-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ordermodel_close_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
    ]
