# Generated by Django 5.2.7 on 2025-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_ordermodel_close_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='close_kline_ms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Свеча сигнала'),
        ),
    ]
