# Generated by Django 5.2.7 on 2025-11-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_ordermodel_close_kline_ms'),
        ('position', '0010_rename_dt_end_positionmodel_close_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='open_kline_ms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Свеча открытия'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='close_kline_ms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Свеча закрытия'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='position.positionmodel', verbose_name='Позиция'),
        ),
    ]
