# Generated by Django 5.2.7 on 2025-10-15 09:58

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('status', django_fsm.FSMField(choices=[('created', 'Создано'), ('monitoring', 'Мониторинг'), ('closed', 'Завершено')], default='created', max_length=50, verbose_name='Статус')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.symbolmodel', verbose_name='Символ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
