# Generated by Django 5.2.7 on 2025-10-15 10:18

import app.position.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionmodel',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='category',
            field=models.CharField(default=1, max_length=20, validators=[app.position.models.validate_category], verbose_name='Рынок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='is_test',
            field=models.BooleanField(default=1, verbose_name='Тест-позиция'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='side',
            field=models.CharField(default=1, max_length=6, validators=[app.position.models.validate_side], verbose_name='Сторона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='uuid',
            field=models.UUIDField(default=1, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
