# Generated by Django 5.2.7 on 2025-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_alter_positionmodel_options_positionmodel_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionmodel',
            old_name='create_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='positionmodel',
            name='update_on',
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
