# Generated by Django 5.2.7 on 2025-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_rename_create_on_positionmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionmodel',
            name='uuid',
            field=models.UUIDField(unique=True, verbose_name='UUID'),
        ),
    ]
