# Generated by Django 5.2.7 on 2025-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_alter_positionmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodel',
            name='qty_tokens',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во токенов'),
            preserve_default=False,
        ),
    ]
