# Generated by Django 5.2.7 on 2025-10-22 15:58

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_positionmodel_qty_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionmodel',
            name='status',
            field=django_fsm.FSMField(choices=[('created', 'Создано'), ('monitoring', 'Мониторинг'), ('completed', 'Исполнено'), ('cancel', 'Отменено')], default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
