# Generated by Django 5.2.7 on 2025-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0006_alter_positionmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionmodel',
            name='uuid',
            field=models.CharField(max_length=40, unique=True, verbose_name='UUID'),
        ),
    ]
