# Generated by Django 5.2.7 on 2025-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_alter_positionmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodel',
            name='kline_ms',
            field=models.CharField(default=1, max_length=100, verbose_name='Свеча сигнала'),
            preserve_default=False,
        ),
    ]
