# Generated by Django 5.2.7 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0008_positionmodel_kline_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodel',
            name='dt_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
    ]
